### ISSUE TITLE
pg_clickhouse fails to compile on PostgreSQL‑15.6: unknown type name 'pg_regex_t'

### ISSUE THREAD

**Issue by fernando1987** [ClickHouse/pg_clickhouse#358]
When building pg_clickhouse against PostgreSQL‑15.6, compile fails in `deparseFuncExpr` of `src/deparse.c`.
The type `pg_regex_t` does not exist in PG 15.6. Using internal non‑exported type leads to incompatible pointer and `re_nsub` member access errors. `-Werror` turns these into build‑stopping errors.
Need version‑gated compatibility for PostgreSQL‑15.

cc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -Wno-declaration-after-statement -Wall -Wclobbered -Wsign-compare -Werror -fPIC -I./src/include -isystem vendor/pg-clickhouse-c/clickhouse-c -isystem vendor/pg-clickhouse-c -isystem /usr/local/pgsql‑15.6/include/server -DPGCH_MSG_PREFIX='"pg_clickhouse: "' -DCHC_ERR_MSG_LEN=4096 -I. -I./ -I/usr/local/pgsql‑15.6/include/server -I/usr/local/pgsql‑15.6/include/internal -D_GNU_SOURCE -c -o src/deparse.o src/deparse.c src/deparse.c: In function 'deparseFuncExpr': src/deparse.c:4599:13: error: unknown type name 'pg_regex_t'; did you mean 'regex_t'? 4599 | pg_regex_t* regex = RE_compile_and_cache( | ^~~~~~~~~~ | regex_t src/deparse.c:4599:33: error: initialization of 'int *' from incompatible pointer type 'regex_t ' [-Werror=incompatible-pointer-types] 4599 | pg_regex_t regex = RE_compile_and_cache( | ^~~~~~~~~~~~~~~~~~~~ src/deparse.c:4608:27: error: request for member 're_nsub' in something not a structure or union 4608 | buf, regex->re_nsub ? "extractGroups(" : "arraySlice(extractAll(" | ^~ src/deparse.c:4613:46: error: request for member 're_nsub' in something not a structure or union 4613 | appendStringInfoString(buf, regex->re_nsub ? ")" : "), 1, 1)"); | ^~ cc1: all warnings being treated as errors make: *** [<builtin>: src/deparse.o] Error 1

**Comment by serprex** [comment]
update to 15.8
